.travis.yml
=> #1 added .travis.yml file

.travis.yml
=> #1 corrected .travis.yml file

pom.xml, src/main/java/com/amihaiemil/camel/StrictYamlMapping.java, src/main/java/com/amihaiemil/camel/YamlMapping.java, src/main/java/com/amihaiemil/camel/YamlNodeNotFoundException.java, src/test/java/com/amihaiemil/camel/StrictYamlMappingTest.java
PR for #22 
Implemented StrictYamlMapping and unit tested it.
=> StrictYamlMapping + unit tests

src/main/java/com/amihaiemil/camel/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/camel/Yaml.java, src/main/java/com/amihaiemil/camel/YamlMappingBuilder.java, src/test/java/com/amihaiemil/camel/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/camel/YamlTest.java
PR for #24 
Left a puzzle for the implementation of YamlSequenceBuilder.
=> RtYamlMappingBuilder and unit tests

src/main/java/com/amihaiemil/camel/RtYamlSequenceBuilder.java, src/main/java/com/amihaiemil/camel/YamlSequenceBuilder.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceBuilderTest.java
=> Implemented sequence builder

src/main/java/com/amihaiemil/camel/Yaml.java, src/main/java/com/amihaiemil/camel/YamlObjectDump.java, src/test/java/com/amihaiemil/camel/YamlMapDumpTest.java, src/test/java/com/amihaiemil/camel/YamlObjectDumpTest.java, src/test/java/com/amihaiemil/camel/YamlTest.java
=> More unit tests

pom.xml, src/main/java/com/amihaiemil/camel/RtYamlMapping.java, src/main/java/com/amihaiemil/camel/RtYamlSequence.java, src/main/java/com/amihaiemil/camel/Scalar.java, src/main/java/com/amihaiemil/camel/StrictYamlMapping.java, src/main/java/com/amihaiemil/camel/StrictYamlSequence.java, src/main/java/com/amihaiemil/camel/YamlNode.java, src/test/java/com/amihaiemil/camel/RtYamlMappingTest.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceTest.java, src/test/resources/complexMapping.yml, src/test/resources/complexSequence.yml, src/test/resources/simpleMapping.yml, src/test/resources/simpleSequence.yml
PR for #36 
Implemented YamlNode.indent(int indentation) to pretty print a YamlNode.
=> YamlNode.indent and unit tests

src/main/java/com/amihaiemil/camel/YamlCollectionDump.java, src/test/java/com/amihaiemil/camel/YamlCollectionDumpTest.java
=> Implemented YamlCollectionDump class

src/main/java/com/amihaiemil/camel/RtYamlInput.java, src/main/java/com/amihaiemil/camel/Yaml.java, src/main/java/com/amihaiemil/camel/YamlInput.java
PR for #46 
+ YamlInput
+ unit tests
=> YamlInput design

src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/main/java/com/amihaiemil/camel/YamlLine.java, src/main/java/com/amihaiemil/camel/YamlLines.java
=> Yaml lines design

src/main/java/com/amihaiemil/camel/WellIndentedLine.java
=> Implemented WellIndentedLine class

src/main/java/com/amihaiemil/camel/EvenlyIndentedLine.java, src/test/java/com/amihaiemil/camel/EvenlyIndentedLineTest.java, src/test/java/com/amihaiemil/camel/WellIndentedLineTest.java
PR for #59 
Also added ``EvenlyIndentedLine`` which checks if the indentation is multiple of 2.
=> Unit tests and bug fix

src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java
=> Implemented nested() method

src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/main/java/com/amihaiemil/camel/YamlMapping.java, src/test/java/com/amihaiemil/camel/ReadYamlMappingTest.java
PR for #63 
Started implementation of ReadYamlMapping
=> ReadYamlMapping and other puzzles

README.md, checkstyle.xml, src/main/java/com/amihaiemil/camel/AbstractYamlLines.java, src/main/java/com/amihaiemil/camel/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/RtYamlInput.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/main/java/com/amihaiemil/camel/YamlLine.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java
PR for #64 
Added ReadYamlSequence, did some refactorings and added some puzzles
=> Added ReadYamlSequence and other puzzles

src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/test/java/com/amihaiemil/camel/ReadYamlMappingTest.java
PR for #67 
Also some refactoring.
=> ReadYamlMapping.yamlSequence(String)

src/main/java/com/amihaiemil/camel/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/main/java/com/amihaiemil/camel/WellIndentedLine.java, src/main/java/com/amihaiemil/camel/YamlLine.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java
=> YamlLine extended Comparable

src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/test/java/com/amihaiemil/camel/ReadYamlMappingTest.java
=>  method ReadYamlMapping.string(String) 

src/main/java/com/amihaiemil/camel/CachedYamlLine.java, src/main/java/com/amihaiemil/camel/CashedYamlLine.java, src/test/java/com/amihaiemil/camel/CachedYamlLineTest.java
=> Implemented CachedYamlLine decorator class

src/main/java/com/amihaiemil/camel/CachedYamlLine.java, src/main/java/com/amihaiemil/camel/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/camel/RtYamlInput.java, src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/main/java/com/amihaiemil/camel/WellIndentedLine.java, src/main/java/com/amihaiemil/camel/YamlLine.java, src/test/java/com/amihaiemil/camel/RtYamlLineTest.java
PR for #82 
Implemented YamlLine.hasNestedNode()
=> YamlLine.hasNestedNode() and unit test

src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/RtYamlSequence.java, src/main/java/com/amihaiemil/camel/StrictYamlSequence.java, src/main/java/com/amihaiemil/camel/YamlSequence.java, src/test/java/com/amihaiemil/camel/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/StrictYamlSequenceTest.java
=> YamlSequence.size() and unit tests

src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/StrictYamlSequence.java, src/test/java/com/amihaiemil/camel/ReadYamlSequenceTest.java
=> ReadYamlSequence finished + unit tests

src/test/java/com/amihaiemil/camel/CachedYamlLineTest.java
=> Used Mockito for testing

src/main/java/com/amihaiemil/camel/CachedYamlLine.java, src/main/java/com/amihaiemil/camel/NoCommentsYamlLine.java, src/main/java/com/amihaiemil/camel/RtYamlInput.java, src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/test/java/com/amihaiemil/camel/NoCommentsYamlLineTest.java, src/test/java/com/amihaiemil/camel/RtYamlInputTest.java, src/test/resources/commentedMapping.yml
=> Usage of NoCommentsYamlLine, unit test and fixes + puzzle

pom.xml, src/main/java/com/amihaiemil/camel/NoCommentsYamlLine.java, src/test/java/com/amihaiemil/camel/NoCommentsYamlLineTest.java, src/test/java/com/amihaiemil/camel/RtYamlInputTest.java
=> Fixed line trimming bug

src/main/java/com/amihaiemil/camel/ReadPipeScalar.java, src/test/java/com/amihaiemil/camel/ReadPipeScalarTest.java
=> Implemented ReadPipeScalar

src/main/java/com/amihaiemil/camel/RtYamlMapping.java, src/main/java/com/amihaiemil/camel/RtYamlSequence.java, src/test/java/com/amihaiemil/camel/RtYamlMappingTest.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceTest.java
=> toString fixed for empty build Yaml

src/main/java/com/amihaiemil/camel/OrderedYamlLines.java, src/test/java/com/amihaiemil/camel/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/camel/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/RtYamlMappingTest.java
=> fixed read yaml empty toString()

src/main/java/com/amihaiemil/camel/AbstractYamlMapping.java, src/main/java/com/amihaiemil/camel/AbstractYamlSequence.java, src/main/java/com/amihaiemil/camel/StrictYamlMapping.java, src/main/java/com/amihaiemil/camel/Yaml.java, src/main/java/com/amihaiemil/camel/YamlCollectionDump.java, src/main/java/com/amihaiemil/camel/YamlMapDump.java, src/main/java/com/amihaiemil/camel/YamlMapping.java, src/main/java/com/amihaiemil/camel/YamlNode.java
=> fixed javadocs

.gitattributes
=> Add .yml eol to .gitattributes

pom.xml
=> Removed unused slf4j dependency

.travis.yml, pom.xml
=> Moved to Java 8

src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java
PR for #156 
YamlSequence can now be iterated. Also added unit tests.
=> #156 YamlSequence is now Iterable

pom.xml
=> #172 commons-beanutils bump to 1.9.4

src/main/java/com/amihaiemil/eoyaml/ComparableYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
PR for #166 
- Made ReadYamlMapping.keys() and RtYamlMapping.keys() return ordered sets.
=> [WIP] Implement Ordering in ReadYamlMapping

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
=> [WIP] Unit tests and fixes for ReadYamlMapping.children()

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java
PR for #176 
* wrote a ton of unit tests for methods .string(...)/.yamlMapping(...)/.yamlSequence(...) from ReadYamlMapping
* fixed bugs in the 3 methods
* a little refactoring
* tests for RtYamlMapping.
=> Fixed and tested ReadYamlMapping.yamlSequence()/.yamlMapping()

src/main/java/com/amihaiemil/eoyaml/ReadPipeScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadPointedScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlNode.java
=> added YamlNode.values() and deprecated children()

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java
=> #183 implemented YamlMapping.value(...) + unit tests

src/main/java/com/amihaiemil/eoyaml/ComparableYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ComparableYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadPipeScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadPointedScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlNode.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadPipeScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPointedScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/ScalarTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/YamlCollectionDumpTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMapDumpTest.java, src/test/java/com/amihaiemil/eoyaml/YamlObjectDumpTest.java
For #180 
Replaced the calls with YamlNode.values() and renamed some tests.
=> For #180 Replaced internal calls to YamlNode.children()

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/indentedComplexMapping.yml
For #166 
Still work-in-progress. We need to at least add some tests for this method.
=> added ReadYamlMapping.indent(int)

src/main/java/com/amihaiemil/eoyaml/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java
=> removed usage of and deprecated EvenlyIndentedLine

src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java
=> removed YamlLines.indent(...)

README.md, pom.xml, src/main/java/com/amihaiemil/eoyaml/ComparableYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlStreamBuilder.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlInput.java, src/main/java/com/amihaiemil/eoyaml/YamlStream.java, src/main/java/com/amihaiemil/eoyaml/YamlStreamBuilder.java, src/test/java/com/amihaiemil/eoyaml/BuiltYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlStreamBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/YamlTest.java, src/test/resources/streamMixed.yml, src/test/resources/streamOfMappings.yml, src/test/resources/streamOfSequences.yml
PR for #90 
* Implemented building of YamlStream. YamlStream also implements the Java 8 Stream!
=> Implement Building of Yaml Streams

src/main/java/com/amihaiemil/eoyaml/NoCommentsYamlLine.java, src/test/java/com/amihaiemil/eoyaml/NoCommentsYamlLineTest.java
=> escape value with apostrophes as well

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalarValue.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/mapping_ignore_directives.yml
=> unescaping read scalar

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlStream.java, src/test/java/com/amihaiemil/eoyaml/BuiltYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java
fixes #204 
Also modified the tests, so they can run on any CI platform or dev setup.
=> #204 NewLine is now Platform-agnostic

src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java
PR for #212 
* fixed reading of empty YamlStream
* added unit tests also for the cases of empty mapping and sequence
=> #212 fixed empty stream case and added more unit tests

src/test/java/com/amihaiemil/eoyaml/BuiltYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java
This PR just fixes some typos.
=> it fixes typos

src/main/java/com/amihaiemil/eoyaml/ComparableScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/test/java/com/amihaiemil/eoyaml/BuiltBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlScalarBuilderTest.java
PR for #227 
- implemented building of both folded and literal block scalars
- added unit tests
- left a few TODOs in the code
=> Finished implementing building of Scalars

src/main/java/com/amihaiemil/eoyaml/NoScalarMarkers.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlInput.java, src/main/java/com/amihaiemil/eoyaml/YamlLine.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/NoScalarMarkersTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java
Fixes #224 
Added scalar readers and unit tests for all cases.
=> #224 scalar readers implemented

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/main/java/com/amihaiemil/eoyaml/exceptions/YamlIndentationException.java, src/main/java/com/amihaiemil/eoyaml/exceptions/YamlReadingException.java, src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java, src/test/java/com/amihaiemil/eoyaml/WellIndentedTest.java
PR for #214 
Adds new YamlReadingException and YamlIndentationException exceptions classes.
=> Adds new exceptions classes

src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/test/java/com/amihaiemil/eoyaml/BuiltFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/BuiltLiteralBlockScalarTest.java
fixes #244 
* split ``BuildBlockScalar`` into ``BuiltFoldedBlockScalar`` and ``BuiltLiteralBlockScalar``
* added unit tests
=> #244 split BuiltBlockScalar and unit tests

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java
Advancements for #230 
We will need to continue with #220 before finishing with 230.
=> Simplified ReadYamlMapping.string(...)

src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java
PR for #220 
Implemented and tested ``YamlSequence.foldedBlockScalar(...)``
=> Implemented and tested YamlSequence.foldedBlockScalar(...)

src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java
PR for #220
Implemented and tested YamlSequence.literalBlockScalar(...)
=> #220 implemented and tested YamlSequence.literalBlockScalar()

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java
Pr for #220 
* implemented ``YamlMapping.foldedBlockScalar(...)``
* implemented ``YamlMapping.literalBlockScalar(...)``
=> #220 YamlMapping accessors for literal/folded block scalar

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java
=> String-Key Methods Made Default

checkstyle.xml, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java
fixes #220 
Added the last needed unit tests.
=> Unit tests for #220

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/MergedYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/extensions/package-info.java, src/test/java/com/amihaiemil/eoyaml/extensions/MergedYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/extensions/MergedYamlSequenceTest.java
fixes #262 
* Implemented and tested ``MergedYamlMapping``
* Implemented and tested ``MergedYamlSequence``
* Pulled out extensions into the ``extensions`` package
=> Introducing Extensions: MergedYamlMapping and MergedYamlSequence

src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BuiltComment.java, src/main/java/com/amihaiemil/eoyaml/Comment.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/BuiltCommentTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/resources/commentedMapping.yml
Fixes #261
* Implemented building of comments in YamlMapping
* implemented printing of comments
* tested printing of built YamlMapping with comments
* left puzzles to continue implementation.
=> Building YamlMapping with Comments

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java
fixes #265 
Comments are now being read and ignored from iteration where needed.
=> #265 read comments and ignore them where needed

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/GreaterIndentation.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/Skip.java, src/main/java/com/amihaiemil/eoyaml/StartMarkers.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/SameIndentationLevelTestCase.java, src/test/java/com/amihaiemil/eoyaml/StartMarkersTest.java, src/test/java/com/amihaiemil/eoyaml/WellIndentedTest.java
=> #284 YamlLines.lines() -> YamlLines.original()

src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java
PR for #279 
work in progress. Still need to implement method ``comment()`` for the Scalars.
=> #279 ReadYamlSequence.comment() implemented

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlNode.java, src/main/java/com/amihaiemil/eoyaml/PlainStringScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/test/java/com/amihaiemil/eoyaml/BuiltFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/BuiltLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/PlainStringScalarTest.java
PR for #288 
Method ``comment()`` implemented in all types of scalar used for building YAML.
=> Method comment() Implemented for Built Scalars

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarValueTest.java
PR for #288 
Implemented and tested method ``comment()`` in all scalars.
Next step: implement building of comments into scalars (modify the scalar builder to also accept comments)
=> Implemented Scalar.comment()

src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlScalarBuilder.java
Fixes #288 
Comments can now be added to scalars when they are built
=> #288 build scalars with comment

src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/Comments.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlNode.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlStream.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java, src/test/resources/commentedMapping.yml, src/test/resources/commentedSequence.yml
Pr for #292
Work in progress, still need to fix printing of child comments.
=> Remove comments() Method

pom.xml, src/main/java9/module-info.java
Add support for Java modules while maintaining Java 8 compatibility.
=> #295 Add Java module support

src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java
=> Fix trailing comments

src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java
=> More Test Cases For Comments

.travis.yml
We updated rultor to jdk 11. Let's see if merging works
=> for merge testing

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlNode.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingBuilderTest.java
PR for #134 
Better support for null/empty values. Handling null or empty keys when building maps.
=> #134 empty values improvement: complain on empty/null key

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java
PR for #134 
* If a value is null or empty, print "null"
* added unit tests
=> Print "null" For Empty/Null YamlNodes

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/RtYamlPrinterTest.java
=> #315 closed the Writer after printing

src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlSequence.java
Fixes #320 
Most of YamlSequence's methods are made default.
=> Default methods for YamlSequence

src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java
Added unit test for reported ticket #327. Bug could not be reproduced.
=> #327 added test for reported bug

src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java
=> #327 ReadLiteralBlockScalar.value() fixed

src/main/java/com/amihaiemil/eoyaml/ReflectedYamlDump.java
It was making your content that'is sequence like that;
```yaml
test: ["...", "....", "...."]
```
with the p.r.
```yaml
test:
- ....
- ....
- ...
```
=> Fix about sequences.

.travis.yml, pom.xml
PR for #365 
Added Travis Build with the latest OpenJDK15 EA Release.
=> #365 Travis script for OpenJDK 15 EA builds

src/main/java/com/amihaiemil/eoyaml/WellIndented.java
=> #371 YamlIndentationException points the lines' contents as well

src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlLineTest.java
=> #374 small workaround

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/escapedScalarsInSequence.yml
=> #382 RegEx escaping issues fixed

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
=> Equals instead of endsWith (and check for - too).

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java, src/test/resources/printing_tests/yamlSequenceAllNodes.txt
Modify BaseScalar to handle escaping with a regex and support matching string of purely spaces. Fixes #376
=> Handle scalar of spaces.

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlPrinterTest.java
=> #422 Fixed bug where values with '?' where not escaped.

pom.xml, src/main/java/com/amihaiemil/eoyaml/JsonYamlDump.java, src/main/java/com/amihaiemil/eoyaml/JsonYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/JsonYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/test/java/com/amihaiemil/eoyaml/JsonYamlDumpTest.java, src/test/java/com/amihaiemil/eoyaml/JsonYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/JsonYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/YamlTest.java
=> #231 Added + tested Yaml.fromJsonObject()

src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/extensions/MergedYamlMappingTest.java
- can override conflicting keys
- when the conflicting keys values are sequences and the override conflicts flag is set, they will be merged into one sequence.
Pr for #420
=> #420 Recursive YamlMapping Merge.

src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/test/java/com/amihaiemil/eoyaml/YamlTest.java
=> #433 Implemented+tested method Yaml.fromJsonArray(JsonArray).

src/main/java/com/amihaiemil/eoyaml/ReadScalarComment.java, src/main/java/com/amihaiemil/eoyaml/ScalarComment.java, src/test/java/com/amihaiemil/eoyaml/ReadScalarCommentTest.java
Fixes #458 
Left puzzle to use this class inside ReadPlainScalar.comment()
=> #458 ReadScalarComment implemented and tested

src/main/java/com/amihaiemil/eoyaml/InlineComment.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/InlineCommentTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java
PR for #457 
Fixed printing of mappings (proper print of scalar key and removed printing of key comments);
Introduced InlineComment and used it inside PlainStringScalar;
Unit tests;
Left puzzle to continue work.
=> #457 InlineComment + unit tests

src/main/java/com/amihaiemil/eoyaml/Concatenated.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/test/java/com/amihaiemil/eoyaml/ConcatenatedTest.java
=> #465 ReadScalarComment => Concatenated

src/main/java/com/amihaiemil/eoyaml/PlainStringScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlScalarBuilder.java, src/test/java/com/amihaiemil/eoyaml/PlainStringScalarTest.java
Fixes #464 
The user can now build a scalar with above *and* inline comments.
=> #464 Build scalar with above and inline comments

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java
PR for #463 
Adjusted printing logic to print ScalarComment properly.
Tests.
=> #463 print ScalarComment

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java
https://github.com/decorators-squad/eo-yaml/issues/479
=> #479 Fix chomping final line break

src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/Skip.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/resources/issue_480_bug_printing.yml
Fixed bug where literal block scalar were not read correctly from string/file.
PR for #480
=> #480 Fixed literal block scalar read bug.

src/main/java/com/amihaiemil/eoyaml/BuiltComment.java, src/main/java/com/amihaiemil/eoyaml/YamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlSequenceBuilder.java
I created this PR to add the functionality to create above YamlNode comments with multiple lines, for example create a Yaml Map File whit a complex "header", the map comment, that has lot of explication lines, this PR give the ability to create a colletion and every element of this colletion is a line of this comment, making it easier to create this complex comment
=> Added Multiple Lines Comment Option

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_494_bracketed_keys.yml
=> #494 Support for bracket notation.

src/main/java/com/amihaiemil/eoyaml/MutableYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/MutableYamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlMappingBuilder.java, src/test/java/com/amihaiemil/eoyaml/MutableYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/MutableYamlSequenceBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/YamlTest.java
=> #512 Added MutableYamlMappingBuilder and MutableYamlSequenceBuilder

src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_525_emptyEntries.yml
This PR provides a unit test for #525
=> Add unit test for issue 525

README.md, src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/Backwards.java, src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/GreaterIndentation.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/Skip.java, src/main/java/com/amihaiemil/eoyaml/StartMarkers.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java, src/test/java/com/amihaiemil/eoyaml/BackwardsTest.java, src/test/java/com/amihaiemil/eoyaml/FirstCommentFoundTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/SkipTest.java, src/test/java/com/amihaiemil/eoyaml/StartMarkersTest.java, src/test/java/com/amihaiemil/eoyaml/WellIndentedTest.java, src/test/java/com/amihaiemil/eoyaml/YamlIndentationTestCase.java
PR for #532 
Removed guessIndentation logic and parameters (incl. public parameters);
Bugfix in WellIndented related to >| inner indentation (ignore indentation when we are within a folded or literal block scalar).
=> #532 remove guessIndentation logic and parameters (incl public params)

src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_497_ghost_comment.yml
=> #497 fixed gost comment in scalars

src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue546.yml, src/test/resources/issue_546_mapping_starts_at_dash.yml
=> Fix mapStartsAtDash regex for Issue 546

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/quotedKeysMax.yml
=> unit tests and small fixes for #488

src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_542_seq_folded_blocks.yml, src/test/resources/issue_542_seq_folded_blocks_mix.yml
PR for #542 
Keep track of reading the folded block scalar, analogous to the fix for #480 in the case of literal block scalars.
=> fix reading of folded block scalars #542

src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_556_seq_folded_blocks.yml
PR for fixing unit test added in #556
=> fix for #556

src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_559_list_of_map.yml
Unit test for #559 with fixed indentation.
=> #559 unit test

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlSequenceTest.java
Fixes #541 
Fixed printing of reflected scalars and added unit tests.
=> #541 fix printing of reflected scalars + unit tests

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java, src/test/resources/printing_tests/yamlCommentsOnMapAndSeqRoundTrip.txt, src/test/resources/printing_tests/yamlCommentsOnMapOrSeqRoundTrip.txt, src/test/resources/printing_tests/yamlDuplicatedCommentsRoundTrip.txt
=> #574 complete reserved chars escape list

pom.xml
=> Fix unit tests (update mockito)

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/JsonYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java
=> #587 fix hashCode NPE for null scalars

src/main/java/com/amihaiemil/eoyaml/JsonYamlDump.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlDump.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlScalar.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlComment.java, src/main/java/com/amihaiemil/eoyaml/YamlDump.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlSequenceTest.java
=> #591 [at]YamlComment Annotation for Reflected YamlNode

src/main/java/com/amihaiemil/eoyaml/BaseYamlNode.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlPrintVisitor.java, src/main/java/com/amihaiemil/eoyaml/YamlVisitor.java
=> #594 RtYamlPrinter uses YamlPrintVisitor internally

src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowMappingTestCase.java
=> #388 Implementing ReadFlowMapping

src/main/java/com/amihaiemil/eoyaml/FlowOnOneLine.java, src/main/java/com/amihaiemil/eoyaml/FoldedFlowLines.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowSequence.java, src/test/java/com/amihaiemil/eoyaml/FlowOnOneLineTestCase.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowMappingTestCase.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowSequenceTestCase.java
#368 Reading of flow style mappings and sequences implemented.
=> #388 #368 ReadFlowMapping and ReadFlowSequence implemented

src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java
=> Addeed more comments.

src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowMappingTestCase.java
=> #601 ReadFlowMappingTestCase implemented

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/sequenceScalarstoSequencesComplexCase.yml
=> #566 Refactored SameIndentationLevel and ReadYamlMapping

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java
=> #612 removed unused WellIndented.guessIndentation attribute

src/main/java/com/amihaiemil/eoyaml/CollapsedFlowLines.java, src/main/java/com/amihaiemil/eoyaml/CollapsedYamlLine.java, src/main/java/com/amihaiemil/eoyaml/FoldedFlowLines.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/CollapsedFlowLinesTestCase.java, src/test/java/com/amihaiemil/eoyaml/CollapsedYamlLineTestCase.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
PR for #607 
We are now able to read flow-style nodes contained within a read bolck-style YamlMapping.
=> #607 Read flow nodes from ReadYamlMapping

src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlPrintVisitor.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowMappingTestCase.java, src/test/resources/typicalSpringApplicationProperties.yml, src/test/resources/typicalSpringApplicationProperties_printed.yml
PR for #605 
Flow mappings and sequences read from somewhere will be printed as such.
=> #605 Implemented printing as flow for read flow nodes

src/main/java/com/amihaiemil/eoyaml/YamlMapping.java
=> #323 Scaffolding for YAML 'loading'
