.travis.yml, pom.xml, src/main/java/com/amihaiemil/camel/AbstractNode.java, src/main/java/com/amihaiemil/camel/Scalar.java, src/test/java/com/amihaiemil/camel/ScalarTest.java
PR for #7 
Implemented AbstractNode which should be extendded by all types of YAML nodes.
Implemented and unit tested Scalar.
Package protected classes since clients are not supposed to see them - YAML objects will be built via builders and later on the processes of loading and dumping will also be encapsulated.
These are first drafts and might change in the near future.
=> AbstractNode, Scalar and unit tests

checkstyle.xml, pom.xml, src/main/java/com/amihaiemil/camel/AbstractNode.java, src/main/java/com/amihaiemil/camel/Scalar.java, src/test/java/com/amihaiemil/camel/ScalarTest.java
PR for #12 
Turned that method abstract because it's more complicated to know a Node's children at its instantiation.
And besides that, a Node always knows its children and can implement the method itself.
e.g. the children of a Mapping node are it's values
=> children() method made abstract + unit test

src/main/java/com/amihaiemil/camel/YamlDump.java, src/main/java/com/amihaiemil/camel/YamlSerializer.java
=> Adding YamlSerializer Interface

src/main/java/com/amihaiemil/camel/AbstractYamlDump.java, src/main/java/com/amihaiemil/camel/YamlMapDump.java, src/main/java/com/amihaiemil/camel/YamlObjectDump.java, src/test/java/com/amihaiemil/camel/YamlMapDumpTest.java
=> Implementing YamlMapDump class 

src/main/java/com/amihaiemil/camel/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/main/java/com/amihaiemil/camel/WellIndentedLine.java, src/main/java/com/amihaiemil/camel/YamlInput.java, src/main/java/com/amihaiemil/camel/YamlLine.java, src/main/java/com/amihaiemil/camel/YamlLines.java, src/main/java/com/amihaiemil/camel/YamlMapping.java, src/main/java/com/amihaiemil/camel/YamlSequence.java, src/test/java/com/amihaiemil/camel/RtYamlLineTest.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java, src/test/java/com/amihaiemil/camel/RtYamlMappingTest.java, src/test/java/com/amihaiemil/camel/WellIndentedLineTest.java
PR for #59 
Also did some refactoring.
``YamlLines`` loses the methods ``toYaml*()``.
Instead, new ``YamlMapping`` and ``YamlSequence`` implementations (left puzzle for them) will work directly with ``YamlLines``. There will also be some caching decorators implemented for them, so the look-up algorithm is not performed every time a method is called.
=> RtYamlLines implemented + unit tests

src/main/java/com/amihaiemil/camel/AbstractYamlMapping.java, src/main/java/com/amihaiemil/camel/AbstractYamlSequence.java, src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/RtYamlMapping.java, src/main/java/com/amihaiemil/camel/RtYamlSequence.java, src/main/java/com/amihaiemil/camel/StrictYamlMapping.java, src/main/java/com/amihaiemil/camel/StrictYamlSequence.java, src/main/java/com/amihaiemil/camel/YamlMapping.java, src/main/java/com/amihaiemil/camel/YamlSequence.java, src/test/java/com/amihaiemil/camel/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceBuilderTest.java, src/test/java/com/amihaiemil/camel/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/camel/StrictYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/YamlCollectionDumpTest.java
PR for #75
Added the 2 classes in order to reuse base methods such as equals and compareTo.
Added method ``AbstractYamlMapping.keys()``
=> AbstractYamlMapping and AbstractYamlSequence

checkstyle.xml, src/main/java/com/amihaiemil/camel/AbstractYamlLines.java, src/main/java/com/amihaiemil/camel/OrderedYamlLines.java, src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/test/java/com/amihaiemil/camel/OrderedYamlLinesTest.java, src/test/java/com/amihaiemil/camel/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java
PR for #73 
Added ``OrderedYamlLines`` decorator, to separate concerns, because having RtYamlLines always ordering the lines is not correct; we don't always want the lines to be ordered - for instance, method ``ReadYamlMapping.string(YamlNode)`` doesn't work right if the lines are ordered
=> Methods in ReadYamlMapping and unit tests

src/main/java/com/amihaiemil/camel/AbstractYamlLines.java, src/main/java/com/amihaiemil/camel/OrderedYamlLines.java, src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/test/java/com/amihaiemil/camel/OrderedYamlLinesTest.java, src/test/java/com/amihaiemil/camel/RtYamlLinesTest.java, src/test/java/com/amihaiemil/camel/ScalarTest.java
PR for #79 
Indentation is implemented within YamlLines, because they also have to be ordered. Also, the lines' indentation logic is common for ReadYamlSequence.
=> Finished implementing ReadYamlMapping

src/main/java/com/amihaiemil/camel/OrderedYamlLines.java, src/main/java/com/amihaiemil/camel/ReadYamlMapping.java, src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/test/java/com/amihaiemil/camel/OrderedYamlLinesTest.java, src/test/java/com/amihaiemil/camel/ReadYamlSequenceTest.java
PR for #70 
Other changes:
+ fixed OrederedYamlLines.iterator() to also order the elements of a sequence
+ fixed ReadYaml*.indent (lines weren't oreder
+ unit test
=> Added ReadYamlSequence.yamlMapping(index)

src/main/java/com/amihaiemil/camel/NoCommentsYamlLine.java, src/test/java/com/amihaiemil/camel/NoCommentsYamlLineTest.java
=> Implemented NoCommentsYamlLine

src/main/java/com/amihaiemil/camel/NestedReadYamlNode.java, src/test/java/com/amihaiemil/camel/NestedReadYamlNodeTest.java
PR for #105 
Implemented NestedReadYamlNode to represent a yaml node nested (intended) after a yaml line.
This way, we'll eventually get rid of AbstractYamlLine.toYamlNode() and also cover all the cases.
=> Nested read yaml node + unit tests and puzzle

src/main/java/com/amihaiemil/camel/ReadPointedScalar.java, src/main/java/com/amihaiemil/camel/RtYamlLine.java, src/test/java/com/amihaiemil/camel/ReadPointedScalarTest.java
=> Implemented ReadPointedScalar

README.md, src/main/java/com/amihaiemil/camel/ReadYamlSequence.java, src/main/java/com/amihaiemil/camel/RtYamlLines.java, src/main/java/com/amihaiemil/camel/RtYamlSequence.java, src/test/java/com/amihaiemil/camel/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/RtYamlInputTest.java, src/test/java/com/amihaiemil/camel/RtYamlMappingTest.java, src/test/java/com/amihaiemil/camel/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/camel/YamlCollectionDumpTest.java
Fixes #129 
YamlSequence now maintains the order of reading or building.
=> Maintain order of YamlSequence

checkstyle.xml, src/main/java/com/amihaiemil/eoyaml/ComparableYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ComparableYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java
PR for #158 
Renamed classes AbstractYamlMapping and AbstractYamlSequence to ComparableYamlMapping and ComparableYamlSequence respectively. 
Also made StrictYamlMapping to work with YamlMapping instead of Abstract(Comparable)YamlMapping.
=> Renamed AbstractMap/Seq -> ComparableMap/Seq

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
For #166 
* ReadYamlMapping.children() reimplemented to lookup the values via keys() method.
- as a consequence, children are also ordered, which is the way it should be
* adapted tests for children() to assert the order
* fixed small bug in keys() method
=> #166 ReadYamlMapping.children() returns ordered children

src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingTypeCastingTestCase.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceTypeCastingTestCase.java
fixes #151 
Convenience Type-Casting Methods for both YamlMapping and YamlSequence. We offer type-casting for: 
* int
* float
* double
* long
* LocalDate
* LocalDateTime.
=> Convenience Type-Casting methods

pom.xml, src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ComparableYamlStream.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/RtYamlStreamBuilder.java, src/main/java/com/amihaiemil/eoyaml/StartMarkers.java, src/main/java/com/amihaiemil/eoyaml/YamlInput.java, src/main/java/com/amihaiemil/eoyaml/YamlStream.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/StartMarkersTest.java
PR for #90
- ``YamlStream`` implements default methods for the Stream API
- ``ReadYamlStream``
- Implemented ``ReadYamlStream.values()`` with the help of ``StartMarkers`` lines decorator
- unit tests
- left puzzles to fix some special cases
=> Reading of YamlStream

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/CachedYamlLine.java, src/main/java/com/amihaiemil/eoyaml/EvenlyIndentedLine.java, src/main/java/com/amihaiemil/eoyaml/NoCommentsYamlLine.java, src/main/java/com/amihaiemil/eoyaml/NoDirectivesOrMarkers.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/main/java/com/amihaiemil/eoyaml/YamlLine.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/RtYamlLineTest.java
pr for #210 
* renamed ``YamlLine.hasNestedNode()`` -> ``YamlLine.requireNestedIndentation()``
* validated the indentation of the Start Markers when reading a Yaml Stream (the values are validated in cascade when each of them are being read)
* made ``YamlLines.nested(...)`` abstract as now it can have multiple different implementations and thus it must be implemented or delegated by each YamlLines implementations.
=> Validate the Indentation of a Read Stream

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/NoDirectives.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/StartMarkers.java, src/test/java/com/amihaiemil/eoyaml/NoDirectivesTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/StartMarkersTest.java, src/test/resources/streamWithComments.yml, src/test/resources/streamWithoutFirstStartMarker.yml
PR for #211 
When reading a YamlStream, the start marker of the first document can be missing.
Wrote unit tests and left 2 puzzles, 1 for refactoring and 1 for fixing a bug regarding YAML Comments and line numbering.
=> Read YamlStream with missing first Start Marker

src/main/java/com/amihaiemil/eoyaml/PlainStringScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java, src/test/java/com/amihaiemil/eoyaml/BuiltYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/PlainStringScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlStreamBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java
PR for #221 
Just a renaming. The BuiltPlainScalar name didn't make sense in all the contexts where this class was used.
=> Renamed BuildPlainScalar to PlainStringScalar

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalarValue.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlStreamBuilder.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlScalarBuilder.java, src/test/java/com/amihaiemil/eoyaml/RtYamlScalarBuilderTest.java
Fixes #221 
* Added ``YamlScalarBuilder`` interface and method ``Yaml.createYamlScalarBuilder()``
* Added implementation ``RtYamlScalarBuilder``
* Implemented ``RtYamlScalarBuilder.buildPlainScalar()``
* Added unit tests
* Left puzzle to continue development of ``buildFolded/LiteralBlockScalar()`` in the next Issue
* Some javadoc fixes across the ``Rt*`` classes
=> Building of Plain Scalars Implemented

src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlNode.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlStream.java, src/main/java/com/amihaiemil/eoyaml/PlainStringScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalarKey.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalarValue.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlScalarBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/BuiltBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/PlainStringScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarKeyTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarValueTest.java
Fixes #229 
* revised toString for mappings, sequences and streams. A final toString() in the base class is ok
* added toString() implementations for all types of Scalar, to print them as YAML documents. So far, if a single Scalar was being printed, the resulted string wasn't actually a valid YAML.
* Made sure that all ``indent(...)`` methods call only other ``indent(...)`` methods, never toString().
* Left javadocs.
* added unit tests for the Scalar toString methods and left puzzle to fix a small bug in ReadFoldedBlockScalar
=> Fixed toString() for Scalars

src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java
PR for #235 
The problem here was that the indented value of this scalar was folded. It's not correct to fold the value when indenting, as the resulting value will be used in printing YAML.
The string should be folded only when it is retreived via the value() method.
=> ReadFoldedBlockScalar.indent() fixed

src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java, src/test/resources/printing_tests/yamlSequenceAllNodes.txt, src/test/resources/printing_tests/yamlSequenceAllNodes.yml
PR for #230 
* we fixed printing of Scalar in the case of YamlSequence
* fixed reading of Scalar in ReadYamlSequence
* added tests for full printing of YamlSequence with all types of nodes we have so far
Next: same fixes for YamlMapping
=> Fixed Scalar Printing for YamlSequence

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java
fixes #255 
* ``valueOfStringKey`` and ``valueOfNodeKey`` can now also search for plain scalars => they cover any kind of value;
* made method ``value(YamlNode)`` use the above 2 methods;
* simplified all other methods by making them use method ``value(YamlNode)``;
Basically, we corrected the flow. Method ``value(...)`` actually reads a generic node and the other values are casting it. Previously, it was the exactly the other way arround.
* Added convenience method ``value(String)`` on the YamlMapping interface;
=> Refactored ReadYamlMapping

src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingPrintTest.java, src/test/resources/printing_tests/yamlMappingAllNodes.txt, src/test/resources/simpleMapping.yml, src/test/resources/streamMixed.yml, src/test/resources/streamOfMappings.yml
fixes #230 
Also ``BaseYamlSequence.indent(...)`` has been fixed. Scalars of any kinds are now printed ok.
=> BaseYamlMapping.indent(...) fixed + fully tested printing

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/test/java/com/amihaiemil/eoyaml/PlainStringScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMapDumpTest.java, src/test/java/com/amihaiemil/eoyaml/YamlObjectDumpTest.java
fixes #239 
Removed the ordering from YamlMappings. The pairs in the map are reflecting their insertion or reading order.
=> YamlMapping Holds Order Of Insetion/Reading

src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java
PR for #219 
* fixed bug in YamlLines.line(int) -- it was matching the index of the line with the provided number, but this was incorrect. It should match the internal number of the line, not its index in the collection.
=> #219 fixed YamlLines.line(...)

src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlSequenceBuilder.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilderTest.java, src/test/java/com/amihaiemil/eoyaml/SkipTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java, src/test/resources/commentedSequence.yml, src/test/resources/complexSequence.yml, src/test/resources/printing_tests/yamlSequenceAllNodes.txt
fixes #276 
* Comments can be specified for each element of the sequence and for the sequence itself when building
* ``YamlSequence.comment()`` returns the comment of the sequence itself
* ``YamlSequence.comments()`` returns the comments referring to the elements of the sequence
* Implemented printing of the comments
* Unit tests for printing + small bugfix regarding trailing spaces.
* Left puzzle to continue implementation for the reading part.
=> YamlSequence: Implemented Building With Comments

src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/BuiltComments.java, src/main/java/com/amihaiemil/eoyaml/Comments.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/BuiltCommentsTest.java
PR for #272 
As a beginning to being able to read comments, we introduced interface ``Comments`` (which is an ``Iterable<Comment>``) instead of a ``List<Comment>`` and its first implementation ``BuiltComments`` (for building)
Reading comments will be performed via the ``ReadComments`` implementation (next PR).
=> List<Comment> => Comments

src/main/java/com/amihaiemil/eoyaml/Backwards.java, src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/ReadComment.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/BackwardsTest.java, src/test/java/com/amihaiemil/eoyaml/FirstCommentFoundTest.java, src/test/java/com/amihaiemil/eoyaml/ReadCommentTest.java, src/test/java/com/amihaiemil/eoyaml/SkipTest.java
For #272 
The comment above a YamlMapping can now be read via the ``comment()`` method
=> Implemented ReadYamlMapping.comment()

src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java
PR for #300 
Work in progress.
The test is currently failing because plain scalars also look for comments above their own line, like a mapping or a sequence. This behaviour turns out to be incorrect -- scalars should look for comments only on their own line, like this:
```yaml
key: value # but this is actually the comment of the scalar, above is the comment of the mapping
```
=> #300 test reading of YamlMapping with comments

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/BaseScalar.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/BaseYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/CachedYamlLine.java, src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/NoCommentsYamlLine.java, src/main/java/com/amihaiemil/eoyaml/ReadComment.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/YamlLine.java, src/test/java/com/amihaiemil/eoyaml/FirstCommentFoundTest.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlLineTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/resources/commentedMapping.yml, src/test/resources/commentedSequence.yml
fixes #302 
In the case of plain scalars, we read only the comment which is on the same line, right after it. Otherwise, the comment's ownership gets messy when we are in the context of a map or a sequence.
=> Read Scalar Comment from Own Line

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/test/java/com/amihaiemil/eoyaml/ReadPlainScalarTest.java
Fixes #134 
Final step:
* read the ``null`` YAML keyword as a Scalar with ``null`` value.
* added unit tests
=> #134 read the null Scalar + tests

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/StrictYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/extensions/MergedYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/StrictYamlMappingTest.java
fixes #317 
All value-accessor methods besides ``value(YamlNode)`` have a default implementation valid for any YamlMapping implementation.
=> YamlMapping new Default Methods

src/main/java/com/amihaiemil/eoyaml/AbstractYamlDump.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlDump.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlScalar.java, src/main/java/com/amihaiemil/eoyaml/ReflectedYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlCollectionDump.java, src/main/java/com/amihaiemil/eoyaml/YamlDump.java, src/main/java/com/amihaiemil/eoyaml/YamlMapDump.java, src/main/java/com/amihaiemil/eoyaml/YamlObjectDump.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlSequenceTest.java
PR for #306 
Implemented Bean-To-Yaml ("dumping") using Reflection API, without 3rd party libs.
=> Implement Bean-to-YAML with Reflection

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java
PR for #327 
Fixed the trimming of the last newline when printing scalars. This should fix the trailing ``\r`` problem on Windows.
=> #327 fixed RtYamlPrinter.indent

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java
PR for #357 
String keys in a  YamlMapping might be escaped (between ``'`` or ``"``).
=> #357 read escaped keys correctly

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/dashMappings.yml
PR for #325 
* Bug fixes in indentation validation logic.
* Fixed the reading of mappings which start right at the dash line in a sequence. E.g. first mapping here:
```yaml
- scalar0
- scalar1
- some: mapping
starting: at-dash
- scalar2
- 
another: mapping
onNext: line
```
=> #325 Fixed mappings starting at dash line in sequences

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/GreaterIndentation.java, src/main/java/com/amihaiemil/eoyaml/Indented.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlStream.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/Skip.java, src/main/java/com/amihaiemil/eoyaml/StartMarkers.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/main/java/com/amihaiemil/eoyaml/YamlLines.java, src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java, src/test/java/com/amihaiemil/eoyaml/BackwardsTest.java, src/test/java/com/amihaiemil/eoyaml/FirstCommentFoundTest.java, src/test/java/com/amihaiemil/eoyaml/SkipTest.java, src/test/java/com/amihaiemil/eoyaml/StartMarkersTest.java, src/test/java/com/amihaiemil/eoyaml/WellIndentedTest.java, src/test/java/com/amihaiemil/eoyaml/YamlIndentationTestCase.java, src/test/resources/badMappingIndentation.yml, src/test/resources/badSequenceIndentationInMapping.yml
PR for #361 
* All the ``Yaml.createYamlInput(...)`` methods have been overriden to accept the boolean flag ``guessIndentation`` -- if this flag is set to true, we will try to "guess" the correct indentation ourselves (i.e. instead of throwing an exception, we will set the expected indentation for each misplaced line).
* TODO: edit the README/Wiki to reflect this change.
=> guessIndentation flag for YamlInput

src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingPrintTest.java, src/test/resources/printing_tests/yamlMappingIndentedComments.yml
PR for #364 
A small bugfix regarding printing of YAML mappings which contain indented comments.
=> #364 fix print with indented comments + test

src/main/java/com/amihaiemil/eoyaml/FirstCommentFound.java, src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/extensions/MergedYamlMappingTest.java, src/test/resources/commentedMapping.yml, src/test/resources/commentedSequence.yml, src/test/resources/mappingWithDocumentComment.yml, src/test/resources/multilineCommentedMapping.yml, src/test/resources/sequenceWithDocumentComment.yml
Fixes #393 
In order to differenciate between the Comment of the overall document and the Comment belonging to the first node, we need to take into account the start-marker of the document (``---``). Before:
```yaml
architects:
- mihai
- sherif
developers:
- mihai
- rultor
- pdd
```
This was causing issues when printing, the first comment was being printed two times.
Now:
```yaml
---
architects:
- mihai
- sherif
developers:
- mihai
- rultor
- pdd
```
=> #393 Differenciate between the Document comment and the comment of the first node

src/main/java/com/amihaiemil/eoyaml/EmptyYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/EmptyYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlMappingBuilder.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/main/java/com/amihaiemil/eoyaml/RtYamlSequenceBuilder.java, src/test/java/com/amihaiemil/eoyaml/EmptyYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/EmptyYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java, src/test/resources/printing_tests/yamlMappingAllNodes.txt, src/test/resources/printing_tests/yamlSequenceAllNodes.txt
This is another blocker. Was getting:
- foo
- {}
Turned into:
- foo
- "{}"
Fixes #383
=> Handle empty mappings and sequences.

src/main/java/com/amihaiemil/eoyaml/CachedYamlLine.java, src/main/java/com/amihaiemil/eoyaml/Indented.java, src/main/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalar.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/main/java/com/amihaiemil/eoyaml/YamlLine.java, src/test/java/com/amihaiemil/eoyaml/CachedYamlLineTest.java, src/test/java/com/amihaiemil/eoyaml/ReadFoldedBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/ReadLiteralBlockScalarTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlLineTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequencePrintTest.java, src/test/resources/printing_tests/yamlSequenceAllNodes.txt
A YamlLine only produces a trimmed version of the content available. For certain scalar values, like block literals you need to keep the spaces and tabs as they can be meaningful as listed in the issue #409 - the link to https://www.yaml.info/learn/quote.html#literal has some good examples.
For example:
```
literal: |
line 1
line 2
```
Should be interpreted as: "line 1\n line 2\n" (there's an extra space before "line 2").
There are also trailing spaces (to the right) that need to be maintained.
The contents method keeps the whitespace characters but keeps track of the indent - so as to remove 2 spaces per indent on the left but keep all the others.
There was a related issue where some of the tests were expecting there not to be a line separator when there should be …
=> Block literals don't print out in a valid way

src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_447_bug_mapping_case_1.yml, src/test/resources/issue_447_bug_mapping_case_2.yml, src/test/resources/issue_447_bug_mapping_case_3.yml, src/test/resources/issue_447_bug_mapping_case_4.yml
PR  for #447
Bug is fixed on yaml lines creation in `RtYamlInput` by moving mapping (key: value) on the next line with an indentation offset of 2 spaces relative to sequence marker.
```yml
- foo: bar
```
becomes:
```yml
-
foo: bar
```
=> #447 Mapping is on same line with sequence marker.

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java, src/test/resources/scalarCommentsInMapping.yml, src/test/resources/scalarCommentsInSequence.yml
Closes #454 
If a scalar has no inline comment, try to read it from above it.
If the scalar does have an inline comment, read that one and ignore the one above it.
Added tests.
Left puzzle for modifying the printing logic of scalar comments.
=> #454 read comments above scalar if inline comment missing

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadScalarComment.java, src/test/java/com/amihaiemil/eoyaml/YamlMappingCommentsPrintTest.java, src/test/java/com/amihaiemil/eoyaml/YamlSequenceCommentsPrintTest.java, src/test/resources/scalarCommentsInMapping.yml, src/test/resources/scalarCommentsInSequence.yml
PR for #460 
ReadPlainScalar.comment() uses ReadScalarComment to concatenate the comment above it and the one inline with it. 
Updated tests.
=> #460 ReadPlainScalar.comment() returns ReadScalarComment

src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/YamlIndentationTestCase.java
Hey 😊
I want to contribute the following test:
Test that a `YamlIndentationException` is thrown.
This tests the methods [`RtYamlLine.indentation`](https://github.com/decorators-squad/eo-yaml/blob/2c088042c3c4cdac75971547186c2f06c9ef1b72/src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java#L132) and [`YamlIndentationException.<init>`](https://github.com/decorators-squad/eo-yaml/blob/2c088042c3c4cdac75971547186c2f06c9ef1b72/src/main/java/com/amihaiemil/eoyaml/exceptions/YamlIndentationException.java#L49).
This test is based on the test [`turnsIntoFoldedSequence`](https://github.com/decorators-squad/eo-yaml/blob/2c088042c3c4cdac75971547186c2f06c9ef1b72/src/test/java/com/amihaiemil/eoyaml/AllYamlLinesTest.java#L115).
Curious to hear what you think!
(I wrote this test as part of a research …
=> Add test for RtYamlLine.indentation and YamlIndentationException.<init>

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/SameIndentationLevel.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_517_values_with_colons.yml
The current version parses keys wrong if a scalar contains a colon. This PR will fix this by checking for a space after the colon of the key name.
This will fix #517
=> #517 The key of an entry must be followed by a space

src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/emptyLiteralScalar.yml
The current implementation fails with an indention error if a YAML contains empty block scalars. This PR fixes this.
=> Do not fail with an indention error if there are emtpy block scalars

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_525_emptyEntries.yml
Fixed bug in empty block/folded scalars when they are nested children.
Left todo to allow keys without values in mappings.
=> Fixes for #525

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/RtYamlLine.java, src/main/java/com/amihaiemil/eoyaml/WellIndented.java, src/test/java/com/amihaiemil/eoyaml/RtYamlLineTest.java, src/test/java/com/amihaiemil/eoyaml/YamlIndentationTestCase.java, src/test/resources/badMappingIndentation.yml
PR for #529 
- Allow empty keys in mapping (this was previously throwing an indentation exaption):
```yaml
architect: amihaiemil
contributors:
developers:
- amihaiemil
- shaik
- rultor
```
- Don't throw exception anymore if sequence under mapping key is not indented properly:
```yaml
architect: amihaiemil
contributors:
developers:
- amihaiemil # these 3 lines should normally have a deeper indentation
- shaik
- rultor
```
- Remove the ``2-by-2`` mandatory indentation. Indentation can now be however many spaces:
```yaml
architect: amihaiemil
contributors:
developers:
- amihaiemil # this indentation works now, previously you would receive an indentation exception
- shaik
- rultor
```
Added TODO to remove the ``guessIndentation`` logic (not needed anymore and it is too unstable anyway).
=> #529 allow empty keys in mapping; lighter indentation rules

src/main/java/com/amihaiemil/eoyaml/ReadPlainScalar.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_547_escaped_special_chars.yml
PR for #547 
Updated regexes to take into account escaped keys (they may contain ``:`` which is misread as YAML symbol);
Added names for the regex groups in ReadYamlScalar, instead of indexes. 
Added unit test to make sure the case of #547 is now valid.
=> #547 regex updates

src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_546_mapping_starts_at_dash_2.yml
PR for #546 (second case, after the first bugfix).
When reading the keys of a mapping, break (instead of continuing iteration) when finding that a sequence starts at the same level.
Added test case.
=> fix for second example in #546

src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/resources/issue_556_seq_folded_blocks.yml
onEvents is a seq, that has a mapping, but parser only can read the first on - eventDataFilter, actions and eventRefs are missed.
=> parsing: missed elements in mapping

src/main/java/com/amihaiemil/eoyaml/YamlLine.java
? case: according to spec, mapping key token must have no token before, so we can check length of the scalar
$ case: according to spec : Comments must be separated from other tokens by white space characters.
so if there is non-white space char, we can assume, it's not a beginning of the comment
WDYT?
=> possible fix for question mask and hash code symbol in scalar

src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java
This returns the YamlNode at position `index` without casting it to a subtype.
I tried to mirror the style of the rest of the file, and to add a unit test.
=> Add method YamlSequence.yamlNode

src/main/java/com/amihaiemil/eoyaml/YamlSequence.java
`yamlMapping` and `yamlSequence` were looping through all elements after arriving at the index'th element; the other methods were looping through the whole sequence when the index'th element was not of the required type.
=> Break out of loop after arriving at the nth element in all cases

src/main/java/com/amihaiemil/eoyaml/RtYamlInput.java, src/main/java/com/amihaiemil/eoyaml/Yaml.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/YamlTest.java
The [YAML spec](https://yaml.org/spec/1.2.2/#52-character-encodings) requires that a YAML processor supports at least UTF-8 and UTF-16. This PR adds this by making the encoding dependant on the `Reader`, allowing for any encoding.
=> Add ability to create `YamlInput` from `Reader`

src/main/java/com/amihaiemil/eoyaml/BaseYamlNode.java, src/main/java/com/amihaiemil/eoyaml/RtYamlPrinter.java, src/main/java/com/amihaiemil/eoyaml/Scalar.java, src/main/java/com/amihaiemil/eoyaml/YamlMapping.java, src/main/java/com/amihaiemil/eoyaml/YamlNode.java, src/main/java/com/amihaiemil/eoyaml/YamlPrintVisitor.java, src/main/java/com/amihaiemil/eoyaml/YamlSequence.java, src/main/java/com/amihaiemil/eoyaml/YamlStream.java, src/main/java/com/amihaiemil/eoyaml/YamlVisitor.java, src/test/java/com/amihaiemil/eoyaml/BuiltYamlStreamTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java, src/test/java/com/amihaiemil/eoyaml/ReflectedYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlInputTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlMappingTest.java, src/test/java/com/amihaiemil/eoyaml/RtYamlSequenceTest.java
PR for #594 
* Introduced the ``YamlVisitor`` interface and scaffolding methods for implementing visiting of any ``YamlNode``;
* Implemented class ``YamlPrintVisitor`` and used it in for ``toString()`` instead of ``RtYamlPrinter``;
=> #594 Visitor pattern and YamlPrintVisitor

src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowSequence.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java
PR for #600 
Started implementing the reading of flow-style nodes from a (block) ReadYamlSequence.
At the moment, only inline flow nodes (starting at the dash) are read. Left TODOs to coved the rest of the cases.
=> #600 start reading of flow-style nodes from a ReadYamlSequence

src/main/java/com/amihaiemil/eoyaml/AllYamlLines.java, src/main/java/com/amihaiemil/eoyaml/ReadYamlSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadYamlSequenceTest.java
PR for #608 
We are now able to fetch flow-style sequences and mappings from a block-style ``ReadYamlSequence``.
Added tests.
=> #608 read flow nodes from a ReadYamlSequence (at the dash and after, inline or multiline)

src/main/java/com/amihaiemil/eoyaml/ReadFlowMapping.java, src/main/java/com/amihaiemil/eoyaml/ReadFlowSequence.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowMappingTestCase.java, src/test/java/com/amihaiemil/eoyaml/ReadFlowSequenceTestCase.java
PR for #618 
First flow nodes can now fetch their parent comment (comment referring to them) or the document comment if they are the only nodes in the file.
=> #618 comment() implemented in Flow nodes
